name: Run all available linters

on: 
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black
        run: |
          black --line-length 120 src/

      - name: Lint with flake8
        run: |
          flake8 src/

      - name: Run Isort
        run: |
          isort src/
