name: Main workflow

on:
  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run Black
        run: |
          pip install -r requirements-dev.txt
          black --line-length 120 --exclude "\.git|\.github|\env|\examples" . --check

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Lint with flake8
        run: |
          pip install -r requirements-dev.txt
          flake8 .

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run Isort
        run: |
          pip install -r requirements-dev.txt
          isort . --check

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Test with pytest
        run: |
          pip install -r requirements.txt
          pytest tests/

  deploy:
    # If the linter job does not pass,the deploy job will not even be executed
    needs: [black, flake, isort, tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploying to Heroku
        # More details available at: https://github.com/marketplace/actions/deploy-to-heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_PROJECT_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL_ADSRESS }}
