name: Test

on: 
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Black
        run: |
          black --line-length 120 src/

      - name: Lint with flake8
        run: |
          flake8 src/

      - name: Isort
        run: |
          isort src/

#  docker-image:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Build docker image
#        run: docker build . -t {{cookiecutter.repo_name}}:test
#
#      - name: Smoke test docker image
#        run: |
#          docker run --rm {{cookiecutter.repo_name}}:test 10